### ISSUE TITLE
Question about detecting unknown subfamily/order

### ISSUE THREAD

**Issue by HLHsieh** [sjteresi/TE_Density#139]
Hi there,

Thank you for providing this tool. I have a question regarding its usage. I am interested in using this tool to detect an unknown subfamily/order sequence. However, as a newcomer to this field, I'm unsure about whether this could apply to this case and how to define the Gene Annotation and TE Annotation. Could you please provide some guidance on this matter? I apologize if this question seems basic.

Thank you in advance for your assistance.

Best regards,
Hsin

**Comment by sjteresi** [comment]
You are trying to identify an unknown TE sequence in your genome? I'm afraid I cannot help there. Or am I misunderstanding?

**Comment by HLHsieh** [comment]
Thank you for your prompt response. Apologies for the unclear description. I'm interested in analyzing the density of a known sequence that is not defined in the TE family by now. My objective is to assess the distribution and abundance of this particular sequence within the genome.

Could you please provide guidance on how to use TE-Density to accomplish this task? I appreciate your assistance.

**Comment by sjteresi** [comment]
Do you have some sort of annotation for your TE of interest?

Currently I do not have immediate plans to implement a calculation for TE families, that will be in the far away future. However that does not mean it is impossible to assess your TE family of interest. Using the following format order/superfamily/family, lets say you have a TE: LTR/Copia/Family001, you could modify your TE annotation to perhaps edit the superfamily name from Copia to Family001. That way when you run TE Density it calculates the value for that particular group and you should have the density values.

Did this answer your question?
