### ISSUE TITLE
Plotting the results in R

### ISSUE THREAD

**Issue by hoyosmanuel** [sjteresi/TE_Density#145]
Hello, thank you very much for creating this software. I would like you to please guide me on how I can plot the final results of transposable element density in R. 
Thanks
Manuel.

**Comment by sjteresi** [comment]
Hi,
I cannot offer much advice on integrating the software with R. I do not plan on adding that feature, however if you figure something out and issue a pull request I would be happy to merge.

I believe there are a number of packages in R that can read/write to HDF5 files (the output file format), but I cannot speak to their usefulness or how well they work. 

Best of luck
