### ISSUE TITLE
OSError during process density

### ISSUE THREAD

**Issue by FlaviaTG** [sjteresi/TE_Density#149]
I am having the following error during process density. I ran the test files, and the program and dependencies are working perfectly. The generated h5 file is truncated?. I would appreciate any help in solving this. Thanks
-------
Traceback (most recent call last):
  File "overlap.py", line 318, in _open_existing_file
    self._h5_file = h5py.File(cfg.filepath, "r")
  File "files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (truncated file: eof = 96, sblock->base_addr = 0, stored_eof = 2048)

**Comment by sjteresi** [comment]
Hello,

I must admit I have not seen this error before. However I have an idea as to why this might be occurring.

Please try deleting the overlap files (these are intermediate calculations) and re-starting the pipeline, I suspect that one of the files was not "finished", i.e the pipeline ran out of time or did not finish on a prior run.

@teresi do you have anything to add?

**Comment by FlaviaTG** [comment]
Fantastic! Thank you so much; deleting the intermediate file in tmp/overlap and re-starting the pipeline worked out.
