### ISSUE TITLE
genome-wide plots

### ISSUE THREAD

**Issue by FlaviaTG** [sjteresi/TE_Density#150]
I want to get a table from the h5 file with three columns: the density, TE order, and the window. I lost information due to the 3D of the h5 dataset when I flattened it to format it as a text file the RHO_ORDERS_LEFT and RHO_ORDERS_RIGHT. However, I still need to figure out how to track back to which TE order corresponds the density value on the matrix text file. My goal is to make a Manhattan-like plot with the TE density. Do you have any guidance on how to achieve this? Or is it not possible? Any other recommendation to visualize the TE density h5 file on a genome-wide scale? I would be wonderful to produce a table that is easy to manipulate in R so I can have several options for visualization.

**Comment by sjteresi** [comment]
Hi,
I have updated the example analysis script located at `examples/general_read_density_data.py` with #152 and suggest you use that. Please update your code to v2.2.1, if you have any issues with TE types not being present for all chromosomes, please take a look at #148 and absorb those changes as that branch is not yet integrated, but I don't anticipate it changing much.

Regarding a Manhattan-like plot I suggest looking at [Matplotlib Scatter Implementation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html). Other visualizations of TE Density on a genome-wide scale could consider recreating the dotplot from the Arabidopsis example in the publication, that is just a call to `plt.plot()` and averages the TE values for all genes for a specific window, direction, and TE type.

**Comment by FlaviaTG** [comment]
Thank you so much for making the h5 output file into a more manageable table format. It's working perfectly now! I have the table, and I can easily plan various types of plots and explore the data. Fantastic tool!

**Comment by sjteresi** [comment]
Thank you, glad I could help.
